/*
This file is automatically generated
AirConPower
C Source
*/

#include "AirConPower.h"

#include "Ft_Gpu.h"
#include "AirConPower_progmem.h"

Ft_Esd_BitmapInfo AirConPower__Info = {
	ESD_BITMAP_DEFAULTS,
	.Width = 32,
	.Height = 32,
	.Format = L2,
	.Stride = 8,
	.Size = 256,
	.ProgMem = AirConPower_bin,
	.StorageSize = ((176 + 3) >> 2),
	.Cells = 1,
	.Compressed = 1,
	.Persistent = 0,
	.Type = ESD_RESOURCE_PROGMEM,
};

Ft_Esd_BitmapCell AirConPower(ft_uint16_t cell)
{
	return (Ft_Esd_BitmapCell){ 
		.Info = &AirConPower__Info, 
		.Cell = cell 
	};
}

#ifdef ESD_SIMULATION
Ft_Esd_BitmapCell AirConPower_0__Get__ESD() { return AirConPower(0); }
#endif

/* end of file */
