/*
This file is automatically generated
alarm_clock1
C Source
*/

#include "alarm_clock1.h"

#include "Ft_Gpu.h"
#include "alarm_clock1_progmem.h"

Ft_Esd_BitmapInfo alarm_clock1__Info = {
	ESD_BITMAP_DEFAULTS,
	.Width = 64,
	.Height = 64,
	.Format = L4,
	.Stride = 32,
	.Size = 2048,
	.ProgMem = alarm_clock1_bin,
	.StorageSize = ((550 + 3) >> 2),
	.Cells = 1,
	.Compressed = 1,
	.Persistent = 0,
	.Type = ESD_RESOURCE_PROGMEM,
};

Ft_Esd_BitmapCell alarm_clock1(ft_uint16_t cell)
{
	return (Ft_Esd_BitmapCell){ 
		.Info = &alarm_clock1__Info, 
		.Cell = cell 
	};
}

#ifdef ESD_SIMULATION
Ft_Esd_BitmapCell alarm_clock1_0__Get__ESD() { return alarm_clock1(0); }
#endif

/* end of file */
