/*
This file is automatically generated
alarm_clock2
Header
*/

#ifndef alarm_clock2__H
#define alarm_clock2__H

#ifndef ESD_FUNCTION
#define ESD_FUNCTION(name, ...)
#endif

#include "Ft_DataTypes.h"
#include "Ft_Esd_BitmapInfo.h"

Ft_Esd_BitmapCell alarm_clock2(ft_uint16_t cell);

extern Ft_Esd_BitmapInfo alarm_clock2__Info;

ESD_FUNCTION(alarm_clock2_0, Type = Ft_Esd_BitmapCell, DisplayName = "alarm_clock2", Include = "alarm_clock2.h", Category = _GroupUserResources, Icon = ":/icons/image.png", Macro)
#define alarm_clock2_0() ((Ft_Esd_BitmapCell){ .Info = &alarm_clock2__Info, .Cell = 0 })

#endif /* alarm_clock2__H */

/* end of file */
