/*
This file is automatically generated
alarm_clock2
C Source
*/

#include "alarm_clock2.h"

#include "Ft_Gpu.h"
#include "alarm_clock2_progmem.h"

Ft_Esd_BitmapInfo alarm_clock2__Info = {
	ESD_BITMAP_DEFAULTS,
	.Width = 64,
	.Height = 64,
	.Format = PALETTED8,
	.Stride = 64,
	.Size = 4096,
	.ProgMem = alarm_clock2_index_bin,
	.StorageSize = ((1438 + 3) >> 2),
	.PaletteProgMem = alarm_clock2_lut_raw,
	.Cells = 1,
	.Compressed = 1,
	.Persistent = 0,
	.Type = ESD_RESOURCE_PROGMEM,
};

Ft_Esd_BitmapCell alarm_clock2(ft_uint16_t cell)
{
	return (Ft_Esd_BitmapCell){ 
		.Info = &alarm_clock2__Info, 
		.Cell = cell 
	};
}

#ifdef ESD_SIMULATION
Ft_Esd_BitmapCell alarm_clock2_0__Get__ESD() { return alarm_clock2(0); }
#endif

/* end of file */
