/*
This file is automatically generated
bedroom_light
Header
*/

#ifndef bedroom_light__H
#define bedroom_light__H

#ifndef ESD_FUNCTION
#define ESD_FUNCTION(name, ...)
#endif

#include "Ft_DataTypes.h"
#include "Ft_Esd_BitmapInfo.h"

Ft_Esd_BitmapCell bedroom_light(ft_uint16_t cell);

extern Ft_Esd_BitmapInfo bedroom_light__Info;

ESD_FUNCTION(bedroom_light_0, Type = Ft_Esd_BitmapCell, DisplayName = "bedroom_light", Include = "bedroom_light.h", Category = _GroupUserResources, Icon = ":/icons/image.png", Macro)
#define bedroom_light_0() ((Ft_Esd_BitmapCell){ .Info = &bedroom_light__Info, .Cell = 0 })

#endif /* bedroom_light__H */

/* end of file */
