/*
This file is automatically generated
Bedroom
Header
*/

#ifndef Bedroom__H
#define Bedroom__H

#ifndef ESD_FUNCTION
#define ESD_FUNCTION(name, ...)
#endif

#include "Ft_DataTypes.h"
#include "Ft_Esd_BitmapInfo.h"

Ft_Esd_BitmapCell Bedroom(ft_uint16_t cell);

extern Ft_Esd_BitmapInfo Bedroom__Info;

ESD_FUNCTION(Bedroom_0, Type = Ft_Esd_BitmapCell, DisplayName = "Bedroom", Include = "Bedroom.h", Category = _GroupUserResources, Icon = ":/icons/image.png", Macro)
#define Bedroom_0() ((Ft_Esd_BitmapCell){ .Info = &Bedroom__Info, .Cell = 0 })

#endif /* Bedroom__H */

/* end of file */
