/*
This file is automatically generated
bedroom_light
C Source
*/

#include "bedroom_light.h"

#include "Ft_Gpu.h"
#include "bedroom_light_progmem.h"

Ft_Esd_BitmapInfo bedroom_light__Info = {
	ESD_BITMAP_DEFAULTS,
	.Width = 156,
	.Height = 93,
	.Format = L2,
	.Stride = 39,
	.Size = 3627,
	.ProgMem = bedroom_light_bin,
	.StorageSize = ((504 + 3) >> 2),
	.Cells = 1,
	.Compressed = 1,
	.Persistent = 0,
	.Type = ESD_RESOURCE_PROGMEM,
};

Ft_Esd_BitmapCell bedroom_light(ft_uint16_t cell)
{
	return (Ft_Esd_BitmapCell){ 
		.Info = &bedroom_light__Info, 
		.Cell = cell 
	};
}

#ifdef ESD_SIMULATION
Ft_Esd_BitmapCell bedroom_light_0__Get__ESD() { return bedroom_light(0); }
#endif

/* end of file */
