/*
This file is automatically generated
Bedroom
C Source
*/

#include "Bedroom.h"

#include "Ft_Gpu.h"
#include "Bedroom_progmem.h"

Ft_Esd_BitmapInfo Bedroom__Info = {
	ESD_BITMAP_DEFAULTS,
	.Width = 480,
	.Height = 480,
	.Format = PALETTED8,
	.Stride = 480,
	.Size = 230400,
	.ProgMem = Bedroom_index_bin,
	.StorageSize = ((20645 + 3) >> 2),
	.PaletteProgMem = Bedroom_lut_raw,
	.Cells = 1,
	.Compressed = 1,
	.Persistent = 0,
	.Type = ESD_RESOURCE_PROGMEM,
};

Ft_Esd_BitmapCell Bedroom(ft_uint16_t cell)
{
	return (Ft_Esd_BitmapCell){ 
		.Info = &Bedroom__Info, 
		.Cell = cell 
	};
}

#ifdef ESD_SIMULATION
Ft_Esd_BitmapCell Bedroom_0__Get__ESD() { return Bedroom(0); }
#endif

/* end of file */
