/*
This file is automatically generated
Bedroom2
Header
*/

#ifndef Bedroom2__H
#define Bedroom2__H

#ifndef ESD_FUNCTION
#define ESD_FUNCTION(name, ...)
#endif

#include "Ft_DataTypes.h"
#include "Ft_Esd_BitmapInfo.h"

Ft_Esd_BitmapCell Bedroom2(ft_uint16_t cell);

extern Ft_Esd_BitmapInfo Bedroom2__Info;

ESD_FUNCTION(Bedroom2_0, Type = Ft_Esd_BitmapCell, DisplayName = "Bedroom2", Include = "Bedroom2.h", Category = _GroupUserResources, Icon = ":/icons/image.png", Macro)
#define Bedroom2_0() ((Ft_Esd_BitmapCell){ .Info = &Bedroom2__Info, .Cell = 0 })

#endif /* Bedroom2__H */

/* end of file */
