/*
This file is automatically generated
Bedroom2
C Source
*/

#include "Bedroom2.h"

#include "Ft_Gpu.h"
#include "Bedroom2_progmem.h"

Ft_Esd_BitmapInfo Bedroom2__Info = {
	ESD_BITMAP_DEFAULTS,
	.Width = 480,
	.Height = 480,
	.Format = PALETTED8,
	.Stride = 480,
	.Size = 230400,
	.ProgMem = Bedroom2_index_bin,
	.StorageSize = ((22026 + 3) >> 2),
	.PaletteProgMem = Bedroom2_lut_raw,
	.Cells = 1,
	.Compressed = 1,
	.Persistent = 0,
	.Type = ESD_RESOURCE_PROGMEM,
};

Ft_Esd_BitmapCell Bedroom2(ft_uint16_t cell)
{
	return (Ft_Esd_BitmapCell){ 
		.Info = &Bedroom2__Info, 
		.Cell = cell 
	};
}

#ifdef ESD_SIMULATION
Ft_Esd_BitmapCell Bedroom2_0__Get__ESD() { return Bedroom2(0); }
#endif

/* end of file */
