/*
This file is automatically generated
CeilingLigehtCase1
Header
*/

#ifndef CeilingLigehtCase1__H
#define CeilingLigehtCase1__H

#ifndef ESD_FUNCTION
#define ESD_FUNCTION(name, ...)
#endif

#include "Ft_DataTypes.h"
#include "Ft_Esd_BitmapInfo.h"

Ft_Esd_BitmapCell CeilingLigehtCase1(ft_uint16_t cell);

extern Ft_Esd_BitmapInfo CeilingLigehtCase1__Info;

ESD_FUNCTION(CeilingLigehtCase1_0, Type = Ft_Esd_BitmapCell, DisplayName = "CeilingLigehtCase1", Include = "CeilingLigehtCase1.h", Category = _GroupUserResources, Icon = ":/icons/image.png", Macro)
#define CeilingLigehtCase1_0() ((Ft_Esd_BitmapCell){ .Info = &CeilingLigehtCase1__Info, .Cell = 0 })

#endif /* CeilingLigehtCase1__H */

/* end of file */
