/*
This file is automatically generated
CeilingLightlshade
Header
*/

#ifndef CeilingLightlshade__H
#define CeilingLightlshade__H

#ifndef ESD_FUNCTION
#define ESD_FUNCTION(name, ...)
#endif

#include "Ft_DataTypes.h"
#include "Ft_Esd_BitmapInfo.h"

Ft_Esd_BitmapCell CeilingLightlshade(ft_uint16_t cell);

extern Ft_Esd_BitmapInfo CeilingLightlshade__Info;

ESD_FUNCTION(CeilingLightlshade_0, Type = Ft_Esd_BitmapCell, DisplayName = "CeilingLightlshade", Include = "CeilingLightlshade.h", Category = _GroupUserResources, Icon = ":/icons/image.png", Macro)
#define CeilingLightlshade_0() ((Ft_Esd_BitmapCell){ .Info = &CeilingLightlshade__Info, .Cell = 0 })

#endif /* CeilingLightlshade__H */

/* end of file */
