/*
This file is automatically generated
CeilingLigehtCase
C Source
*/

#include "CeilingLigehtCase.h"

#include "Ft_Gpu.h"
#include "CeilingLigehtCase_progmem.h"

Ft_Esd_BitmapInfo CeilingLigehtCase__Info = {
	ESD_BITMAP_DEFAULTS,
	.Width = 165, /* Padded to 166, REPEAT will not work as expected */
	.Height = 65,
	.Format = L4,
	.Stride = 83,
	.Size = 5395,
	.ProgMem = CeilingLigehtCase_bin,
	.StorageSize = ((1836 + 3) >> 2),
	.Cells = 1,
	.Compressed = 1,
	.Persistent = 0,
	.Type = ESD_RESOURCE_PROGMEM,
};

Ft_Esd_BitmapCell CeilingLigehtCase(ft_uint16_t cell)
{
	return (Ft_Esd_BitmapCell){ 
		.Info = &CeilingLigehtCase__Info, 
		.Cell = cell 
	};
}

#ifdef ESD_SIMULATION
Ft_Esd_BitmapCell CeilingLigehtCase_0__Get__ESD() { return CeilingLigehtCase(0); }
#endif

/* end of file */
