/*
This file is automatically generated
Ceiling
C Source
*/

#include "Ceiling.h"

#include "Ft_Gpu.h"
#include "Ceiling_progmem.h"

Ft_Esd_BitmapInfo Ceiling__Info = {
	ESD_BITMAP_DEFAULTS,
	.Width = 480,
	.Height = 480,
	.Format = PALETTED8,
	.Stride = 480,
	.Size = 230400,
	.ProgMem = Ceiling_index_raw,
	.StorageSize = ((230400 + 3) >> 2),
	.PaletteProgMem = Ceiling_lut_raw,
	.Cells = 1,
	.Compressed = 0,
	.Persistent = 0,
	.Type = ESD_RESOURCE_PROGMEM,
};

Ft_Esd_BitmapCell Ceiling(ft_uint16_t cell)
{
	return (Ft_Esd_BitmapCell){ 
		.Info = &Ceiling__Info, 
		.Cell = cell 
	};
}

#ifdef ESD_SIMULATION
Ft_Esd_BitmapCell Ceiling_0__Get__ESD() { return Ceiling(0); }
#endif

/* end of file */
