/*
This file is automatically generated
CeilingLigehtCase1
C Source
*/

#include "CeilingLigehtCase1.h"

#include "Ft_Gpu.h"
#include "CeilingLigehtCase1_progmem.h"

Ft_Esd_BitmapInfo CeilingLigehtCase1__Info = {
	ESD_BITMAP_DEFAULTS,
	.Width = 183, /* Padded to 184, REPEAT will not work as expected */
	.Height = 47,
	.Format = L4,
	.Stride = 92,
	.Size = 4324,
	.ProgMem = CeilingLigehtCase1_bin,
	.StorageSize = ((1702 + 3) >> 2),
	.Cells = 1,
	.Compressed = 1,
	.Persistent = 0,
	.Type = ESD_RESOURCE_PROGMEM,
};

Ft_Esd_BitmapCell CeilingLigehtCase1(ft_uint16_t cell)
{
	return (Ft_Esd_BitmapCell){ 
		.Info = &CeilingLigehtCase1__Info, 
		.Cell = cell 
	};
}

#ifdef ESD_SIMULATION
Ft_Esd_BitmapCell CeilingLigehtCase1_0__Get__ESD() { return CeilingLigehtCase1(0); }
#endif

/* end of file */
