/*
This file is automatically generated
CeilingLigehtCase
Header
*/

#ifndef CeilingLigehtCase__H
#define CeilingLigehtCase__H

#ifndef ESD_FUNCTION
#define ESD_FUNCTION(name, ...)
#endif

#include "Ft_DataTypes.h"
#include "Ft_Esd_BitmapInfo.h"

Ft_Esd_BitmapCell CeilingLigehtCase(ft_uint16_t cell);

extern Ft_Esd_BitmapInfo CeilingLigehtCase__Info;

ESD_FUNCTION(CeilingLigehtCase_0, Type = Ft_Esd_BitmapCell, DisplayName = "CeilingLigehtCase", Include = "CeilingLigehtCase.h", Category = _GroupUserResources, Icon = ":/icons/image.png", Macro)
#define CeilingLigehtCase_0() ((Ft_Esd_BitmapCell){ .Info = &CeilingLigehtCase__Info, .Cell = 0 })

#endif /* CeilingLigehtCase__H */

/* end of file */
