/*
This file is automatically generated
CeilingLightWire
Header
*/

#ifndef CeilingLightWire__H
#define CeilingLightWire__H

#ifndef ESD_FUNCTION
#define ESD_FUNCTION(name, ...)
#endif

#include "Ft_DataTypes.h"
#include "Ft_Esd_BitmapInfo.h"

Ft_Esd_BitmapCell CeilingLightWire(ft_uint16_t cell);

extern Ft_Esd_BitmapInfo CeilingLightWire__Info;

ESD_FUNCTION(CeilingLightWire_0, Type = Ft_Esd_BitmapCell, DisplayName = "CeilingLightWire", Include = "CeilingLightWire.h", Category = _GroupUserResources, Icon = ":/icons/image.png", Macro)
#define CeilingLightWire_0() ((Ft_Esd_BitmapCell){ .Info = &CeilingLightWire__Info, .Cell = 0 })

#endif /* CeilingLightWire__H */

/* end of file */
