/*
This file is automatically generated
Ceiling
Header
*/

#ifndef Ceiling__H
#define Ceiling__H

#ifndef ESD_FUNCTION
#define ESD_FUNCTION(name, ...)
#endif

#include "Ft_DataTypes.h"
#include "Ft_Esd_BitmapInfo.h"

Ft_Esd_BitmapCell Ceiling(ft_uint16_t cell);

extern Ft_Esd_BitmapInfo Ceiling__Info;

ESD_FUNCTION(Ceiling_0, Type = Ft_Esd_BitmapCell, DisplayName = "Ceiling", Include = "Ceiling.h", Category = _GroupUserResources, Icon = ":/icons/image.png", Macro)
#define Ceiling_0() ((Ft_Esd_BitmapCell){ .Info = &Ceiling__Info, .Cell = 0 })

#endif /* Ceiling__H */

/* end of file */
