/*
This file is automatically generated
CeilingLightWire
C Source
*/

#include "CeilingLightWire.h"

#include "Ft_Gpu.h"
#include "CeilingLightWire_progmem.h"

Ft_Esd_BitmapInfo CeilingLightWire__Info = {
	ESD_BITMAP_DEFAULTS,
	.Width = 8,
	.Height = 59,
	.Format = L4,
	.Stride = 4,
	.Size = 236,
	.ProgMem = CeilingLightWire_bin,
	.StorageSize = ((98 + 3) >> 2),
	.Cells = 1,
	.Compressed = 1,
	.Persistent = 0,
	.Type = ESD_RESOURCE_PROGMEM,
};

Ft_Esd_BitmapCell CeilingLightWire(ft_uint16_t cell)
{
	return (Ft_Esd_BitmapCell){ 
		.Info = &CeilingLightWire__Info, 
		.Cell = cell 
	};
}

#ifdef ESD_SIMULATION
Ft_Esd_BitmapCell CeilingLightWire_0__Get__ESD() { return CeilingLightWire(0); }
#endif

/* end of file */
