/*
This file is automatically generated
CeilingLightlshade1
C Source
*/

#include "CeilingLightlshade1.h"

#include "Ft_Gpu.h"
#include "CeilingLightlshade1_progmem.h"

Ft_Esd_BitmapInfo CeilingLightlshade1__Info = {
	ESD_BITMAP_DEFAULTS,
	.Width = 54,
	.Height = 55,
	.Format = L4,
	.Stride = 27,
	.Size = 1485,
	.ProgMem = CeilingLightlshade1_bin,
	.StorageSize = ((948 + 3) >> 2),
	.Cells = 1,
	.Compressed = 1,
	.Persistent = 0,
	.Type = ESD_RESOURCE_PROGMEM,
};

Ft_Esd_BitmapCell CeilingLightlshade1(ft_uint16_t cell)
{
	return (Ft_Esd_BitmapCell){ 
		.Info = &CeilingLightlshade1__Info, 
		.Cell = cell 
	};
}

#ifdef ESD_SIMULATION
Ft_Esd_BitmapCell CeilingLightlshade1_0__Get__ESD() { return CeilingLightlshade1(0); }
#endif

/* end of file */
