/*
This file is automatically generated
CeilingLightCase2
Header
*/

#ifndef CeilingLightCase2__H
#define CeilingLightCase2__H

#ifndef ESD_FUNCTION
#define ESD_FUNCTION(name, ...)
#endif

#include "Ft_DataTypes.h"
#include "Ft_Esd_BitmapInfo.h"

Ft_Esd_BitmapCell CeilingLightCase2(ft_uint16_t cell);

extern Ft_Esd_BitmapInfo CeilingLightCase2__Info;

ESD_FUNCTION(CeilingLightCase2_0, Type = Ft_Esd_BitmapCell, DisplayName = "CeilingLightCase2", Include = "CeilingLightCase2.h", Category = _GroupUserResources, Icon = ":/icons/image.png", Macro)
#define CeilingLightCase2_0() ((Ft_Esd_BitmapCell){ .Info = &CeilingLightCase2__Info, .Cell = 0 })

#endif /* CeilingLightCase2__H */

/* end of file */
