/*
This file is automatically generated
CeilingLightlshade1
Header
*/

#ifndef CeilingLightlshade1__H
#define CeilingLightlshade1__H

#ifndef ESD_FUNCTION
#define ESD_FUNCTION(name, ...)
#endif

#include "Ft_DataTypes.h"
#include "Ft_Esd_BitmapInfo.h"

Ft_Esd_BitmapCell CeilingLightlshade1(ft_uint16_t cell);

extern Ft_Esd_BitmapInfo CeilingLightlshade1__Info;

ESD_FUNCTION(CeilingLightlshade1_0, Type = Ft_Esd_BitmapCell, DisplayName = "CeilingLightlshade1", Include = "CeilingLightlshade1.h", Category = _GroupUserResources, Icon = ":/icons/image.png", Macro)
#define CeilingLightlshade1_0() ((Ft_Esd_BitmapCell){ .Info = &CeilingLightlshade1__Info, .Cell = 0 })

#endif /* CeilingLightlshade1__H */

/* end of file */
