/*
This file is automatically generated
circle
C Source
*/

#include "circle.h"

#include "Ft_Gpu.h"
#include "circle_progmem.h"

Ft_Esd_BitmapInfo circle__Info = {
	ESD_BITMAP_DEFAULTS,
	.Width = 140,
	.Height = 140,
	.Format = PALETTED8,
	.Stride = 140,
	.Size = 19600,
	.ProgMem = circle_index_bin,
	.StorageSize = ((2132 + 3) >> 2),
	.PaletteProgMem = circle_lut_raw,
	.Cells = 1,
	.Compressed = 1,
	.Persistent = 0,
	.Type = ESD_RESOURCE_PROGMEM,
};

Ft_Esd_BitmapCell circle(ft_uint16_t cell)
{
	return (Ft_Esd_BitmapCell){ 
		.Info = &circle__Info, 
		.Cell = cell 
	};
}

#ifdef ESD_SIMULATION
Ft_Esd_BitmapCell circle_0__Get__ESD() { return circle(0); }
#endif

/* end of file */
