/*
This file is automatically generated
circle
Header
*/

#ifndef circle__H
#define circle__H

#ifndef ESD_FUNCTION
#define ESD_FUNCTION(name, ...)
#endif

#include "Ft_DataTypes.h"
#include "Ft_Esd_BitmapInfo.h"

Ft_Esd_BitmapCell circle(ft_uint16_t cell);

extern Ft_Esd_BitmapInfo circle__Info;

ESD_FUNCTION(circle_0, Type = Ft_Esd_BitmapCell, DisplayName = "circle", Include = "circle.h", Category = _GroupUserResources, Icon = ":/icons/image.png", Macro)
#define circle_0() ((Ft_Esd_BitmapCell){ .Info = &circle__Info, .Cell = 0 })

#endif /* circle__H */

/* end of file */
