/*
This file is automatically generated
CoolPage
C Source
*/

#include "CoolPage.h"

#include "Ft_Gpu.h"
#include "CoolPage_progmem.h"

Ft_Esd_BitmapInfo CoolPage__Info = {
	ESD_BITMAP_DEFAULTS,
	.Width = 480,
	.Height = 477,
	.Format = PALETTED8,
	.Stride = 480,
	.Size = 228960,
	.ProgMem = CoolPage_index_bin,
	.StorageSize = ((15395 + 3) >> 2),
	.PaletteProgMem = CoolPage_lut_raw,
	.Cells = 1,
	.Compressed = 1,
	.Persistent = 0,
	.Type = ESD_RESOURCE_PROGMEM,
};

Ft_Esd_BitmapCell CoolPage(ft_uint16_t cell)
{
	return (Ft_Esd_BitmapCell){ 
		.Info = &CoolPage__Info, 
		.Cell = cell 
	};
}

#ifdef ESD_SIMULATION
Ft_Esd_BitmapCell CoolPage_0__Get__ESD() { return CoolPage(0); }
#endif

/* end of file */
