/*
This file is automatically generated
CoolPage
Header
*/

#ifndef CoolPage__H
#define CoolPage__H

#ifndef ESD_FUNCTION
#define ESD_FUNCTION(name, ...)
#endif

#include "Ft_DataTypes.h"
#include "Ft_Esd_BitmapInfo.h"

Ft_Esd_BitmapCell CoolPage(ft_uint16_t cell);

extern Ft_Esd_BitmapInfo CoolPage__Info;

ESD_FUNCTION(CoolPage_0, Type = Ft_Esd_BitmapCell, DisplayName = "CoolPage", Include = "CoolPage.h", Category = _GroupUserResources, Icon = ":/icons/image.png", Macro)
#define CoolPage_0() ((Ft_Esd_BitmapCell){ .Info = &CoolPage__Info, .Cell = 0 })

#endif /* CoolPage__H */

/* end of file */
