/*
This file is automatically generated
Curtain_adjust
C Source
*/

#include "Curtain_adjust.h"

#include "Ft_Gpu.h"
#include "Curtain_adjust_progmem.h"

Ft_Esd_BitmapInfo Curtain_adjust__Info = {
	ESD_BITMAP_DEFAULTS,
	.Width = 30,
	.Height = 32,
	.Format = PALETTED8,
	.Stride = 30,
	.Size = 960,
	.ProgMem = Curtain_adjust_index_bin,
	.StorageSize = ((605 + 3) >> 2),
	.PaletteProgMem = Curtain_adjust_lut_raw,
	.Cells = 1,
	.Compressed = 1,
	.Persistent = 0,
	.Type = ESD_RESOURCE_PROGMEM,
};

Ft_Esd_BitmapCell Curtain_adjust(ft_uint16_t cell)
{
	return (Ft_Esd_BitmapCell){ 
		.Info = &Curtain_adjust__Info, 
		.Cell = cell 
	};
}

#ifdef ESD_SIMULATION
Ft_Esd_BitmapCell Curtain_adjust_0__Get__ESD() { return Curtain_adjust(0); }
#endif

/* end of file */
