/*
This file is automatically generated
curtain_close_home
Header
*/

#ifndef curtain_close_home__H
#define curtain_close_home__H

#ifndef ESD_FUNCTION
#define ESD_FUNCTION(name, ...)
#endif

#include "Ft_DataTypes.h"
#include "Ft_Esd_BitmapInfo.h"

Ft_Esd_BitmapCell curtain_close_home(ft_uint16_t cell);

extern Ft_Esd_BitmapInfo curtain_close_home__Info;

ESD_FUNCTION(curtain_close_home_0, Type = Ft_Esd_BitmapCell, DisplayName = "curtain_close_home", Include = "curtain_close_home.h", Category = _GroupUserResources, Icon = ":/icons/image.png", Macro)
#define curtain_close_home_0() ((Ft_Esd_BitmapCell){ .Info = &curtain_close_home__Info, .Cell = 0 })

#endif /* curtain_close_home__H */

/* end of file */
