/*
This file is automatically generated
curtain
C Source
*/

#include "curtain.h"

#include "Ft_Gpu.h"
#include "curtain_progmem.h"

Ft_Esd_BitmapInfo curtain__Info = {
	ESD_BITMAP_DEFAULTS,
	.Width = 98,
	.Height = 62,
	.Format = L4,
	.Stride = 49,
	.Size = 3038,
	.ProgMem = curtain_bin,
	.StorageSize = ((499 + 3) >> 2),
	.Cells = 1,
	.Compressed = 1,
	.Persistent = 0,
	.Type = ESD_RESOURCE_PROGMEM,
};

Ft_Esd_BitmapCell curtain(ft_uint16_t cell)
{
	return (Ft_Esd_BitmapCell){ 
		.Info = &curtain__Info, 
		.Cell = cell 
	};
}

#ifdef ESD_SIMULATION
Ft_Esd_BitmapCell curtain_0__Get__ESD() { return curtain(0); }
#endif

/* end of file */
