/*
This file is automatically generated
CurtainPage
Header
*/

#ifndef CurtainPage__H
#define CurtainPage__H

#ifndef ESD_FUNCTION
#define ESD_FUNCTION(name, ...)
#endif

#include "Ft_DataTypes.h"
#include "Ft_Esd_BitmapInfo.h"

Ft_Esd_BitmapCell CurtainPage(ft_uint16_t cell);

extern Ft_Esd_BitmapInfo CurtainPage__Info;

ESD_FUNCTION(CurtainPage_0, Type = Ft_Esd_BitmapCell, DisplayName = "CurtainPage", Include = "CurtainPage.h", Category = _GroupUserResources, Icon = ":/icons/image.png", Macro)
#define CurtainPage_0() ((Ft_Esd_BitmapCell){ .Info = &CurtainPage__Info, .Cell = 0 })

#endif /* CurtainPage__H */

/* end of file */
