/*
This file is automatically generated
curtain_open1
C Source
*/

#include "curtain_open1.h"

#include "Ft_Gpu.h"
#include "curtain_open1_progmem.h"

Ft_Esd_BitmapInfo curtain_open1__Info = {
	ESD_BITMAP_DEFAULTS,
	.Width = 64,
	.Height = 58,
	.Format = PALETTED8,
	.Stride = 64,
	.Size = 3712,
	.ProgMem = curtain_open1_index_bin,
	.StorageSize = ((441 + 3) >> 2),
	.PaletteProgMem = curtain_open1_lut_raw,
	.Cells = 1,
	.Compressed = 1,
	.Persistent = 0,
	.Type = ESD_RESOURCE_PROGMEM,
};

Ft_Esd_BitmapCell curtain_open1(ft_uint16_t cell)
{
	return (Ft_Esd_BitmapCell){ 
		.Info = &curtain_open1__Info, 
		.Cell = cell 
	};
}

#ifdef ESD_SIMULATION
Ft_Esd_BitmapCell curtain_open1_0__Get__ESD() { return curtain_open1(0); }
#endif

/* end of file */
