/*
This file is automatically generated
CurtainClosed
Header
*/

#ifndef CurtainClosed__H
#define CurtainClosed__H

#ifndef ESD_FUNCTION
#define ESD_FUNCTION(name, ...)
#endif

#include "Ft_DataTypes.h"
#include "Ft_Esd_BitmapInfo.h"

Ft_Esd_BitmapCell CurtainClosed(ft_uint16_t cell);

extern Ft_Esd_BitmapInfo CurtainClosed__Info;

ESD_FUNCTION(CurtainClosed_0, Type = Ft_Esd_BitmapCell, DisplayName = "CurtainClosed", Include = "CurtainClosed.h", Category = _GroupUserResources, Icon = ":/icons/image.png", Macro)
#define CurtainClosed_0() ((Ft_Esd_BitmapCell){ .Info = &CurtainClosed__Info, .Cell = 0 })

#endif /* CurtainClosed__H */

/* end of file */
