/*
This file is automatically generated
curtain_open_home2
Header
*/

#ifndef curtain_open_home2__H
#define curtain_open_home2__H

#ifndef ESD_FUNCTION
#define ESD_FUNCTION(name, ...)
#endif

#include "Ft_DataTypes.h"
#include "Ft_Esd_BitmapInfo.h"

Ft_Esd_BitmapCell curtain_open_home2(ft_uint16_t cell);

extern Ft_Esd_BitmapInfo curtain_open_home2__Info;

ESD_FUNCTION(curtain_open_home2_0, Type = Ft_Esd_BitmapCell, DisplayName = "curtain_open_home2", Include = "curtain_open_home2.h", Category = _GroupUserResources, Icon = ":/icons/image.png", Macro)
#define curtain_open_home2_0() ((Ft_Esd_BitmapCell){ .Info = &curtain_open_home2__Info, .Cell = 0 })

#endif /* curtain_open_home2__H */

/* end of file */
