/*
This file is automatically generated
curtain_open_home2
C Source
*/

#include "curtain_open_home2.h"

#include "Ft_Gpu.h"
#include "curtain_open_home2_progmem.h"

Ft_Esd_BitmapInfo curtain_open_home2__Info = {
	ESD_BITMAP_DEFAULTS,
	.Width = 98,
	.Height = 62,
	.Format = PALETTED8,
	.Stride = 98,
	.Size = 6076,
	.ProgMem = curtain_open_home2_index_bin,
	.StorageSize = ((1085 + 3) >> 2),
	.PaletteProgMem = curtain_open_home2_lut_raw,
	.Cells = 1,
	.Compressed = 1,
	.Persistent = 0,
	.Type = ESD_RESOURCE_PROGMEM,
};

Ft_Esd_BitmapCell curtain_open_home2(ft_uint16_t cell)
{
	return (Ft_Esd_BitmapCell){ 
		.Info = &curtain_open_home2__Info, 
		.Cell = cell 
	};
}

#ifdef ESD_SIMULATION
Ft_Esd_BitmapCell curtain_open_home2_0__Get__ESD() { return curtain_open_home2(0); }
#endif

/* end of file */
