/*
This file is automatically generated
curtain
Header
*/

#ifndef curtain__H
#define curtain__H

#ifndef ESD_FUNCTION
#define ESD_FUNCTION(name, ...)
#endif

#include "Ft_DataTypes.h"
#include "Ft_Esd_BitmapInfo.h"

Ft_Esd_BitmapCell curtain(ft_uint16_t cell);

extern Ft_Esd_BitmapInfo curtain__Info;

ESD_FUNCTION(curtain_0, Type = Ft_Esd_BitmapCell, DisplayName = "curtain", Include = "curtain.h", Category = _GroupUserResources, Icon = ":/icons/image.png", Macro)
#define curtain_0() ((Ft_Esd_BitmapCell){ .Info = &curtain__Info, .Cell = 0 })

#endif /* curtain__H */

/* end of file */
