/*
This file is automatically generated
Curtain_hand_pull
C Source
*/

#include "Curtain_hand_pull.h"

#include "Ft_Gpu.h"
#include "Curtain_hand_pull_progmem.h"

Ft_Esd_BitmapInfo Curtain_hand_pull__Info = {
	ESD_BITMAP_DEFAULTS,
	.Width = 40,
	.Height = 36,
	.Format = PALETTED8,
	.Stride = 40,
	.Size = 1440,
	.ProgMem = Curtain_hand_pull_index_bin,
	.StorageSize = ((538 + 3) >> 2),
	.PaletteProgMem = Curtain_hand_pull_lut_raw,
	.Cells = 1,
	.Compressed = 1,
	.Persistent = 0,
	.Type = ESD_RESOURCE_PROGMEM,
};

Ft_Esd_BitmapCell Curtain_hand_pull(ft_uint16_t cell)
{
	return (Ft_Esd_BitmapCell){ 
		.Info = &Curtain_hand_pull__Info, 
		.Cell = cell 
	};
}

#ifdef ESD_SIMULATION
Ft_Esd_BitmapCell Curtain_hand_pull_0__Get__ESD() { return Curtain_hand_pull(0); }
#endif

/* end of file */
