/*
This file is automatically generated
curtain_open_home5
C Source
*/

#include "curtain_open_home5.h"

#include "Ft_Gpu.h"
#include "curtain_open_home5_progmem.h"

Ft_Esd_BitmapInfo curtain_open_home5__Info = {
	ESD_BITMAP_DEFAULTS,
	.Width = 100,
	.Height = 63,
	.Format = PALETTED8,
	.Stride = 100,
	.Size = 6300,
	.ProgMem = curtain_open_home5_index_bin,
	.StorageSize = ((1038 + 3) >> 2),
	.PaletteProgMem = curtain_open_home5_lut_raw,
	.Cells = 1,
	.Compressed = 1,
	.Persistent = 0,
	.Type = ESD_RESOURCE_PROGMEM,
};

Ft_Esd_BitmapCell curtain_open_home5(ft_uint16_t cell)
{
	return (Ft_Esd_BitmapCell){ 
		.Info = &curtain_open_home5__Info, 
		.Cell = cell 
	};
}

#ifdef ESD_SIMULATION
Ft_Esd_BitmapCell curtain_open_home5_0__Get__ESD() { return curtain_open_home5(0); }
#endif

/* end of file */
