/*
This file is automatically generated
curtain2
C Source
*/

#include "curtain2.h"

#include "Ft_Gpu.h"
#include "curtain2_progmem.h"

Ft_Esd_BitmapInfo curtain2__Info = {
	ESD_BITMAP_DEFAULTS,
	.Width = 100,
	.Height = 66,
	.Format = PALETTED8,
	.Stride = 100,
	.Size = 6600,
	.ProgMem = curtain2_index_bin,
	.StorageSize = ((2363 + 3) >> 2),
	.PaletteProgMem = curtain2_lut_raw,
	.Cells = 1,
	.Compressed = 1,
	.Persistent = 0,
	.Type = ESD_RESOURCE_PROGMEM,
};

Ft_Esd_BitmapCell curtain2(ft_uint16_t cell)
{
	return (Ft_Esd_BitmapCell){ 
		.Info = &curtain2__Info, 
		.Cell = cell 
	};
}

#ifdef ESD_SIMULATION
Ft_Esd_BitmapCell curtain2_0__Get__ESD() { return curtain2(0); }
#endif

/* end of file */
