/*
This file is automatically generated
CurtainPage
C Source
*/

#include "CurtainPage.h"

#include "Ft_Gpu.h"
#include "CurtainPage_progmem.h"

Ft_Esd_BitmapInfo CurtainPage__Info = {
	ESD_BITMAP_DEFAULTS,
	.Width = 480,
	.Height = 480,
	.Format = PALETTED8,
	.Stride = 480,
	.Size = 230400,
	.ProgMem = CurtainPage_index_bin,
	.StorageSize = ((21243 + 3) >> 2),
	.PaletteProgMem = CurtainPage_lut_raw,
	.Cells = 1,
	.Compressed = 1,
	.Persistent = 0,
	.Type = ESD_RESOURCE_PROGMEM,
};

Ft_Esd_BitmapCell CurtainPage(ft_uint16_t cell)
{
	return (Ft_Esd_BitmapCell){ 
		.Info = &CurtainPage__Info, 
		.Cell = cell 
	};
}

#ifdef ESD_SIMULATION
Ft_Esd_BitmapCell CurtainPage_0__Get__ESD() { return CurtainPage(0); }
#endif

/* end of file */
