/*
This file is automatically generated
curtain2
Header
*/

#ifndef curtain2__H
#define curtain2__H

#ifndef ESD_FUNCTION
#define ESD_FUNCTION(name, ...)
#endif

#include "Ft_DataTypes.h"
#include "Ft_Esd_BitmapInfo.h"

Ft_Esd_BitmapCell curtain2(ft_uint16_t cell);

extern Ft_Esd_BitmapInfo curtain2__Info;

ESD_FUNCTION(curtain2_0, Type = Ft_Esd_BitmapCell, DisplayName = "curtain2", Include = "curtain2.h", Category = _GroupUserResources, Icon = ":/icons/image.png", Macro)
#define curtain2_0() ((Ft_Esd_BitmapCell){ .Info = &curtain2__Info, .Cell = 0 })

#endif /* curtain2__H */

/* end of file */
