/*
This file is automatically generated
fan5
Header
*/

#ifndef fan5__H
#define fan5__H

#ifndef ESD_FUNCTION
#define ESD_FUNCTION(name, ...)
#endif

#include "Ft_DataTypes.h"
#include "Ft_Esd_BitmapInfo.h"

Ft_Esd_BitmapCell fan5(ft_uint16_t cell);

extern Ft_Esd_BitmapInfo fan5__Info;

ESD_FUNCTION(fan5_0, Type = Ft_Esd_BitmapCell, DisplayName = "fan5", Include = "fan5.h", Category = _GroupUserResources, Icon = ":/icons/image.png", Macro)
#define fan5_0() ((Ft_Esd_BitmapCell){ .Info = &fan5__Info, .Cell = 0 })

#endif /* fan5__H */

/* end of file */
