/*
This file is automatically generated
fan_icon
C Source
*/

#include "fan_icon.h"

#include "Ft_Gpu.h"
#include "fan_icon_progmem.h"

Ft_Esd_BitmapInfo fan_icon__Info = {
	ESD_BITMAP_DEFAULTS,
	.Width = 40,
	.Height = 40,
	.Format = L2,
	.Stride = 10,
	.Size = 400,
	.ProgMem = fan_icon_bin,
	.StorageSize = ((226 + 3) >> 2),
	.Cells = 1,
	.Compressed = 1,
	.Persistent = 0,
	.Type = ESD_RESOURCE_PROGMEM,
};

Ft_Esd_BitmapCell fan_icon(ft_uint16_t cell)
{
	return (Ft_Esd_BitmapCell){ 
		.Info = &fan_icon__Info, 
		.Cell = cell 
	};
}

#ifdef ESD_SIMULATION
Ft_Esd_BitmapCell fan_icon_0__Get__ESD() { return fan_icon(0); }
#endif

/* end of file */
