/*
This file is automatically generated
floor_heating2
C Source
*/

#include "floor_heating2.h"

#include "Ft_Gpu.h"
#include "floor_heating2_progmem.h"

Ft_Esd_BitmapInfo floor_heating2__Info = {
	ESD_BITMAP_DEFAULTS,
	.Width = 55,
	.Height = 36,
	.Format = PALETTED8,
	.Stride = 55,
	.Size = 1980,
	.ProgMem = floor_heating2_index_bin,
	.StorageSize = ((1289 + 3) >> 2),
	.PaletteProgMem = floor_heating2_lut_raw,
	.Cells = 1,
	.Compressed = 1,
	.Persistent = 0,
	.Type = ESD_RESOURCE_PROGMEM,
};

Ft_Esd_BitmapCell floor_heating2(ft_uint16_t cell)
{
	return (Ft_Esd_BitmapCell){ 
		.Info = &floor_heating2__Info, 
		.Cell = cell 
	};
}

#ifdef ESD_SIMULATION
Ft_Esd_BitmapCell floor_heating2_0__Get__ESD() { return floor_heating2(0); }
#endif

/* end of file */
