/*
This file is automatically generated
funtion_icon
C Source
*/

#include "funtion_icon.h"

#include "Ft_Gpu.h"
#include "funtion_icon_progmem.h"

Ft_Esd_BitmapInfo funtion_icon__Info = {
	ESD_BITMAP_DEFAULTS,
	.Width = 64,
	.Height = 65,
	.Format = L2,
	.Stride = 16,
	.Size = 1040,
	.ProgMem = funtion_icon_bin,
	.StorageSize = ((340 + 3) >> 2),
	.Cells = 1,
	.Compressed = 1,
	.Persistent = 0,
	.Type = ESD_RESOURCE_PROGMEM,
};

Ft_Esd_BitmapCell funtion_icon(ft_uint16_t cell)
{
	return (Ft_Esd_BitmapCell){ 
		.Info = &funtion_icon__Info, 
		.Cell = cell 
	};
}

#ifdef ESD_SIMULATION
Ft_Esd_BitmapCell funtion_icon_0__Get__ESD() { return funtion_icon(0); }
#endif

/* end of file */
