/*
This file is automatically generated
heat_icon
C Source
*/

#include "heat_icon.h"

#include "Ft_Gpu.h"
#include "heat_icon_progmem.h"

Ft_Esd_BitmapInfo heat_icon__Info = {
	ESD_BITMAP_DEFAULTS,
	.Width = 52,
	.Height = 52,
	.Format = L2,
	.Stride = 13,
	.Size = 676,
	.ProgMem = heat_icon_bin,
	.StorageSize = ((195 + 3) >> 2),
	.Cells = 1,
	.Compressed = 1,
	.Persistent = 0,
	.Type = ESD_RESOURCE_PROGMEM,
};

Ft_Esd_BitmapCell heat_icon(ft_uint16_t cell)
{
	return (Ft_Esd_BitmapCell){ 
		.Info = &heat_icon__Info, 
		.Cell = cell 
	};
}

#ifdef ESD_SIMULATION
Ft_Esd_BitmapCell heat_icon_0__Get__ESD() { return heat_icon(0); }
#endif

/* end of file */
