/*
This file is automatically generated
HomePageNew
Header
*/

#ifndef HomePageNew__H
#define HomePageNew__H

#ifndef ESD_FUNCTION
#define ESD_FUNCTION(name, ...)
#endif

#include "Ft_DataTypes.h"
#include "Ft_Esd_BitmapInfo.h"

Ft_Esd_BitmapCell HomePageNew(ft_uint16_t cell);

extern Ft_Esd_BitmapInfo HomePageNew__Info;

ESD_FUNCTION(HomePageNew_0, Type = Ft_Esd_BitmapCell, DisplayName = "HomePageNew", Include = "HomePageNew.h", Category = _GroupUserResources, Icon = ":/icons/image.png", Macro)
#define HomePageNew_0() ((Ft_Esd_BitmapCell){ .Info = &HomePageNew__Info, .Cell = 0 })

#endif /* HomePageNew__H */

/* end of file */
