/*
This file is automatically generated
HomeBG
Header
*/

#ifndef HomeBG__H
#define HomeBG__H

#ifndef ESD_FUNCTION
#define ESD_FUNCTION(name, ...)
#endif

#include "Ft_DataTypes.h"
#include "Ft_Esd_BitmapInfo.h"

Ft_Esd_BitmapCell HomeBG(ft_uint16_t cell);

extern Ft_Esd_BitmapInfo HomeBG__Info;

ESD_FUNCTION(HomeBG_0, Type = Ft_Esd_BitmapCell, DisplayName = "HomeBG", Include = "HomeBG.h", Category = _GroupUserResources, Icon = ":/icons/image.png", Macro)
#define HomeBG_0() ((Ft_Esd_BitmapCell){ .Info = &HomeBG__Info, .Cell = 0 })

#endif /* HomeBG__H */

/* end of file */
