/*
This file is automatically generated
HomePage2
C Source
*/

#include "HomePage2.h"

#include "Ft_Gpu.h"
#include "HomePage2_progmem.h"

Ft_Esd_BitmapInfo HomePage2__Info = {
	ESD_BITMAP_DEFAULTS,
	.Width = 480,
	.Height = 480,
	.Format = PALETTED8,
	.Stride = 480,
	.Size = 230400,
	.ProgMem = HomePage2_index_raw,
	.StorageSize = ((230400 + 3) >> 2),
	.PaletteProgMem = HomePage2_lut_raw,
	.Cells = 1,
	.Compressed = 0,
	.Persistent = 0,
	.Type = ESD_RESOURCE_PROGMEM,
};

Ft_Esd_BitmapCell HomePage2(ft_uint16_t cell)
{
	return (Ft_Esd_BitmapCell){ 
		.Info = &HomePage2__Info, 
		.Cell = cell 
	};
}

#ifdef ESD_SIMULATION
Ft_Esd_BitmapCell HomePage2_0__Get__ESD() { return HomePage2(0); }
#endif

/* end of file */
