/*
This file is automatically generated
HomePage2
Header
*/

#ifndef HomePage2__H
#define HomePage2__H

#ifndef ESD_FUNCTION
#define ESD_FUNCTION(name, ...)
#endif

#include "Ft_DataTypes.h"
#include "Ft_Esd_BitmapInfo.h"

Ft_Esd_BitmapCell HomePage2(ft_uint16_t cell);

extern Ft_Esd_BitmapInfo HomePage2__Info;

ESD_FUNCTION(HomePage2_0, Type = Ft_Esd_BitmapCell, DisplayName = "HomePage2", Include = "HomePage2.h", Category = _GroupUserResources, Icon = ":/icons/image.png", Macro)
#define HomePage2_0() ((Ft_Esd_BitmapCell){ .Info = &HomePage2__Info, .Cell = 0 })

#endif /* HomePage2__H */

/* end of file */
