/*
This file is automatically generated
HomePageNew
C Source
*/

#include "HomePageNew.h"

#include "Ft_Gpu.h"
#include "HomePageNew_progmem.h"

Ft_Esd_BitmapInfo HomePageNew__Info = {
	ESD_BITMAP_DEFAULTS,
	.Width = 480,
	.Height = 480,
	.Format = PALETTED8,
	.Stride = 480,
	.Size = 230400,
	.ProgMem = HomePageNew_index_bin,
	.StorageSize = ((27888 + 3) >> 2),
	.PaletteProgMem = HomePageNew_lut_raw,
	.Cells = 1,
	.Compressed = 1,
	.Persistent = 0,
	.Type = ESD_RESOURCE_PROGMEM,
};

Ft_Esd_BitmapCell HomePageNew(ft_uint16_t cell)
{
	return (Ft_Esd_BitmapCell){ 
		.Info = &HomePageNew__Info, 
		.Cell = cell 
	};
}

#ifdef ESD_SIMULATION
Ft_Esd_BitmapCell HomePageNew_0__Get__ESD() { return HomePageNew(0); }
#endif

/* end of file */
