/*
This file is automatically generated
HomeBG
C Source
*/

#include "HomeBG.h"

#include "Ft_Gpu.h"
#include "HomeBG_progmem.h"

Ft_Esd_BitmapInfo HomeBG__Info = {
	ESD_BITMAP_DEFAULTS,
	.Width = 480,
	.Height = 480,
	.Format = PALETTED8,
	.Stride = 480,
	.Size = 230400,
	.ProgMem = HomeBG_index_raw,
	.StorageSize = ((230400 + 3) >> 2),
	.PaletteProgMem = HomeBG_lut_raw,
	.Cells = 1,
	.Compressed = 0,
	.Persistent = 0,
	.Type = ESD_RESOURCE_PROGMEM,
};

Ft_Esd_BitmapCell HomeBG(ft_uint16_t cell)
{
	return (Ft_Esd_BitmapCell){ 
		.Info = &HomeBG__Info, 
		.Cell = cell 
	};
}

#ifdef ESD_SIMULATION
Ft_Esd_BitmapCell HomeBG_0__Get__ESD() { return HomeBG(0); }
#endif

/* end of file */
