/*
This file is automatically generated
humid_icon
C Source
*/

#include "humid_icon.h"

#include "Ft_Gpu.h"
#include "humid_icon_progmem.h"

Ft_Esd_BitmapInfo humid_icon__Info = {
	ESD_BITMAP_DEFAULTS,
	.Width = 32,
	.Height = 46,
	.Format = L2,
	.Stride = 8,
	.Size = 368,
	.ProgMem = humid_icon_bin,
	.StorageSize = ((182 + 3) >> 2),
	.Cells = 1,
	.Compressed = 1,
	.Persistent = 0,
	.Type = ESD_RESOURCE_PROGMEM,
};

Ft_Esd_BitmapCell humid_icon(ft_uint16_t cell)
{
	return (Ft_Esd_BitmapCell){ 
		.Info = &humid_icon__Info, 
		.Cell = cell 
	};
}

#ifdef ESD_SIMULATION
Ft_Esd_BitmapCell humid_icon_0__Get__ESD() { return humid_icon(0); }
#endif

/* end of file */
