/*
This file is automatically generated
left_curtain1
Header
*/

#ifndef left_curtain1__H
#define left_curtain1__H

#ifndef ESD_FUNCTION
#define ESD_FUNCTION(name, ...)
#endif

#include "Ft_DataTypes.h"
#include "Ft_Esd_BitmapInfo.h"

Ft_Esd_BitmapCell left_curtain1(ft_uint16_t cell);

extern Ft_Esd_BitmapInfo left_curtain1__Info;

ESD_FUNCTION(left_curtain1_0, Type = Ft_Esd_BitmapCell, DisplayName = "left_curtain1", Include = "left_curtain1.h", Category = _GroupUserResources, Icon = ":/icons/image.png", Macro)
#define left_curtain1_0() ((Ft_Esd_BitmapCell){ .Info = &left_curtain1__Info, .Cell = 0 })

#endif /* left_curtain1__H */

/* end of file */
