/*
This file is automatically generated
left_curtain1
C Source
*/

#include "left_curtain1.h"

#include "Ft_Gpu.h"
#include "left_curtain1_progmem.h"

Ft_Esd_BitmapInfo left_curtain1__Info = {
	ESD_BITMAP_DEFAULTS,
	.Width = 160,
	.Height = 200,
	.Format = PALETTED8,
	.Stride = 160,
	.Size = 32000,
	.ProgMem = left_curtain1_index_bin,
	.StorageSize = ((20832 + 3) >> 2),
	.PaletteProgMem = left_curtain1_lut_raw,
	.Cells = 1,
	.Compressed = 1,
	.Persistent = 0,
	.Type = ESD_RESOURCE_PROGMEM,
};

Ft_Esd_BitmapCell left_curtain1(ft_uint16_t cell)
{
	return (Ft_Esd_BitmapCell){ 
		.Info = &left_curtain1__Info, 
		.Cell = cell 
	};
}

#ifdef ESD_SIMULATION
Ft_Esd_BitmapCell left_curtain1_0__Get__ESD() { return left_curtain1(0); }
#endif

/* end of file */
