/*
This file is automatically generated
light
C Source
*/

#include "light.h"

#include "Ft_Gpu.h"
#include "light_progmem.h"

Ft_Esd_BitmapInfo light__Info = {
	ESD_BITMAP_DEFAULTS,
	.Width = 72,
	.Height = 97,
	.Format = L2,
	.Stride = 18,
	.Size = 1746,
	.ProgMem = light_bin,
	.StorageSize = ((328 + 3) >> 2),
	.Cells = 1,
	.Compressed = 1,
	.Persistent = 0,
	.Type = ESD_RESOURCE_PROGMEM,
};

Ft_Esd_BitmapCell light(ft_uint16_t cell)
{
	return (Ft_Esd_BitmapCell){ 
		.Info = &light__Info, 
		.Cell = cell 
	};
}

#ifdef ESD_SIMULATION
Ft_Esd_BitmapCell light_0__Get__ESD() { return light(0); }
#endif

/* end of file */
