/*
This file is automatically generated
light
Header
*/

#ifndef light__H
#define light__H

#ifndef ESD_FUNCTION
#define ESD_FUNCTION(name, ...)
#endif

#include "Ft_DataTypes.h"
#include "Ft_Esd_BitmapInfo.h"

Ft_Esd_BitmapCell light(ft_uint16_t cell);

extern Ft_Esd_BitmapInfo light__Info;

ESD_FUNCTION(light_0, Type = Ft_Esd_BitmapCell, DisplayName = "light", Include = "light.h", Category = _GroupUserResources, Icon = ":/icons/image.png", Macro)
#define light_0() ((Ft_Esd_BitmapCell){ .Info = &light__Info, .Cell = 0 })

#endif /* light__H */

/* end of file */
