/*
This file is automatically generated
light_page_on
C Source
*/

#include "light_page_on.h"

#include "Ft_Gpu.h"
#include "light_page_on_progmem.h"

Ft_Esd_BitmapInfo light_page_on__Info = {
	ESD_BITMAP_DEFAULTS,
	.Width = 45,
	.Height = 35,
	.Format = PALETTED8,
	.Stride = 45,
	.Size = 1575,
	.ProgMem = light_page_on_index_bin,
	.StorageSize = ((1070 + 3) >> 2),
	.PaletteProgMem = light_page_on_lut_raw,
	.Cells = 1,
	.Compressed = 1,
	.Persistent = 0,
	.Type = ESD_RESOURCE_PROGMEM,
};

Ft_Esd_BitmapCell light_page_on(ft_uint16_t cell)
{
	return (Ft_Esd_BitmapCell){ 
		.Info = &light_page_on__Info, 
		.Cell = cell 
	};
}

#ifdef ESD_SIMULATION
Ft_Esd_BitmapCell light_page_on_0__Get__ESD() { return light_page_on(0); }
#endif

/* end of file */
