/*
This file is automatically generated
LightCase
C Source
*/

#include "LightCase.h"

#include "Ft_Gpu.h"
#include "LightCase_progmem.h"

Ft_Esd_BitmapInfo LightCase__Info = {
	ESD_BITMAP_DEFAULTS,
	.Width = 77,
	.Height = 43,
	.Format = PALETTED8,
	.Stride = 77,
	.Size = 3311,
	.ProgMem = LightCase_index_bin,
	.StorageSize = ((790 + 3) >> 2),
	.PaletteProgMem = LightCase_lut_raw,
	.Cells = 1,
	.Compressed = 1,
	.Persistent = 0,
	.Type = ESD_RESOURCE_PROGMEM,
};

Ft_Esd_BitmapCell LightCase(ft_uint16_t cell)
{
	return (Ft_Esd_BitmapCell){ 
		.Info = &LightCase__Info, 
		.Cell = cell 
	};
}

#ifdef ESD_SIMULATION
Ft_Esd_BitmapCell LightCase_0__Get__ESD() { return LightCase(0); }
#endif

/* end of file */
