/*
This file is automatically generated
light_case_ceiling
Header
*/

#ifndef light_case_ceiling__H
#define light_case_ceiling__H

#ifndef ESD_FUNCTION
#define ESD_FUNCTION(name, ...)
#endif

#include "Ft_DataTypes.h"
#include "Ft_Esd_BitmapInfo.h"

Ft_Esd_BitmapCell light_case_ceiling(ft_uint16_t cell);

extern Ft_Esd_BitmapInfo light_case_ceiling__Info;

ESD_FUNCTION(light_case_ceiling_0, Type = Ft_Esd_BitmapCell, DisplayName = "light_case_ceiling", Include = "light_case_ceiling.h", Category = _GroupUserResources, Icon = ":/icons/image.png", Macro)
#define light_case_ceiling_0() ((Ft_Esd_BitmapCell){ .Info = &light_case_ceiling__Info, .Cell = 0 })

#endif /* light_case_ceiling__H */

/* end of file */
