/*
This file is automatically generated
light_case_40
C Source
*/

#include "light_case_40.h"

#include "Ft_Gpu.h"
#include "light_case_40_progmem.h"

Ft_Esd_BitmapInfo light_case_40__Info = {
	ESD_BITMAP_DEFAULTS,
	.Width = 40,
	.Height = 22,
	.Format = PALETTED8,
	.Stride = 40,
	.Size = 880,
	.ProgMem = light_case_40_index_bin,
	.StorageSize = ((299 + 3) >> 2),
	.PaletteProgMem = light_case_40_lut_raw,
	.Cells = 1,
	.Compressed = 1,
	.Persistent = 0,
	.Type = ESD_RESOURCE_PROGMEM,
};

Ft_Esd_BitmapCell light_case_40(ft_uint16_t cell)
{
	return (Ft_Esd_BitmapCell){ 
		.Info = &light_case_40__Info, 
		.Cell = cell 
	};
}

#ifdef ESD_SIMULATION
Ft_Esd_BitmapCell light_case_40_0__Get__ESD() { return light_case_40(0); }
#endif

/* end of file */
