/*
This file is automatically generated
LightPage1
Header
*/

#ifndef LightPage1__H
#define LightPage1__H

#ifndef ESD_FUNCTION
#define ESD_FUNCTION(name, ...)
#endif

#include "Ft_DataTypes.h"
#include "Ft_Esd_BitmapInfo.h"

Ft_Esd_BitmapCell LightPage1(ft_uint16_t cell);

extern Ft_Esd_BitmapInfo LightPage1__Info;

ESD_FUNCTION(LightPage1_0, Type = Ft_Esd_BitmapCell, DisplayName = "LightPage1", Include = "LightPage1.h", Category = _GroupUserResources, Icon = ":/icons/image.png", Macro)
#define LightPage1_0() ((Ft_Esd_BitmapCell){ .Info = &LightPage1__Info, .Cell = 0 })

#endif /* LightPage1__H */

/* end of file */
