/*
This file is automatically generated
livingroom_light_case
C Source
*/

#include "livingroom_light_case.h"

#include "Ft_Gpu.h"
#include "livingroom_light_case_progmem.h"

Ft_Esd_BitmapInfo livingroom_light_case__Info = {
	ESD_BITMAP_DEFAULTS,
	.Width = 164,
	.Height = 105,
	.Format = PALETTED8,
	.Stride = 164,
	.Size = 17220,
	.ProgMem = livingroom_light_case_index_bin,
	.StorageSize = ((1543 + 3) >> 2),
	.PaletteProgMem = livingroom_light_case_lut_raw,
	.Cells = 1,
	.Compressed = 1,
	.Persistent = 0,
	.Type = ESD_RESOURCE_PROGMEM,
};

Ft_Esd_BitmapCell livingroom_light_case(ft_uint16_t cell)
{
	return (Ft_Esd_BitmapCell){ 
		.Info = &livingroom_light_case__Info, 
		.Cell = cell 
	};
}

#ifdef ESD_SIMULATION
Ft_Esd_BitmapCell livingroom_light_case_0__Get__ESD() { return livingroom_light_case(0); }
#endif

/* end of file */
