/*
This file is automatically generated
Livingroom
C Source
*/

#include "Livingroom.h"

#include "Ft_Gpu.h"
#include "Livingroom_progmem.h"

Ft_Esd_BitmapInfo Livingroom__Info = {
	ESD_BITMAP_DEFAULTS,
	.Width = 480,
	.Height = 480,
	.Format = PALETTED8,
	.Stride = 480,
	.Size = 230400,
	.ProgMem = Livingroom_index_bin,
	.StorageSize = ((19839 + 3) >> 2),
	.PaletteProgMem = Livingroom_lut_raw,
	.Cells = 1,
	.Compressed = 1,
	.Persistent = 0,
	.Type = ESD_RESOURCE_PROGMEM,
};

Ft_Esd_BitmapCell Livingroom(ft_uint16_t cell)
{
	return (Ft_Esd_BitmapCell){ 
		.Info = &Livingroom__Info, 
		.Cell = cell 
	};
}

#ifdef ESD_SIMULATION
Ft_Esd_BitmapCell Livingroom_0__Get__ESD() { return Livingroom(0); }
#endif

/* end of file */
