/*
This file is automatically generated
open_curtain
C Source
*/

#include "open_curtain.h"

#include "Ft_Gpu.h"
#include "open_curtain_progmem.h"

Ft_Esd_BitmapInfo open_curtain__Info = {
	ESD_BITMAP_DEFAULTS,
	.Width = 90,
	.Height = 63,
	.Format = PALETTED8,
	.Stride = 90,
	.Size = 5670,
	.ProgMem = open_curtain_index_bin,
	.StorageSize = ((574 + 3) >> 2),
	.PaletteProgMem = open_curtain_lut_raw,
	.Cells = 1,
	.Compressed = 1,
	.Persistent = 0,
	.Type = ESD_RESOURCE_PROGMEM,
};

Ft_Esd_BitmapCell open_curtain(ft_uint16_t cell)
{
	return (Ft_Esd_BitmapCell){ 
		.Info = &open_curtain__Info, 
		.Cell = cell 
	};
}

#ifdef ESD_SIMULATION
Ft_Esd_BitmapCell open_curtain_0__Get__ESD() { return open_curtain(0); }
#endif

/* end of file */
