/*
This file is automatically generated
power_64
C Source
*/

#include "power_64.h"

#include "Ft_Gpu.h"
#include "power_64_progmem.h"

Ft_Esd_BitmapInfo power_64__Info = {
	ESD_BITMAP_DEFAULTS,
	.Width = 64,
	.Height = 64,
	.Format = L4,
	.Stride = 32,
	.Size = 2048,
	.ProgMem = power_64_bin,
	.StorageSize = ((722 + 3) >> 2),
	.Cells = 1,
	.Compressed = 1,
	.Persistent = 0,
	.Type = ESD_RESOURCE_PROGMEM,
};

Ft_Esd_BitmapCell power_64(ft_uint16_t cell)
{
	return (Ft_Esd_BitmapCell){ 
		.Info = &power_64__Info, 
		.Cell = cell 
	};
}

#ifdef ESD_SIMULATION
Ft_Esd_BitmapCell power_64_0__Get__ESD() { return power_64(0); }
#endif

/* end of file */
