/*
This file is automatically generated
power
C Source
*/

#include "power.h"

#include "Ft_Gpu.h"
#include "power_progmem.h"

Ft_Esd_BitmapInfo power__Info = {
	ESD_BITMAP_DEFAULTS,
	.Width = 64,
	.Height = 54,
	.Format = L2,
	.Stride = 16,
	.Size = 864,
	.ProgMem = power_bin,
	.StorageSize = ((265 + 3) >> 2),
	.Cells = 1,
	.Compressed = 1,
	.Persistent = 0,
	.Type = ESD_RESOURCE_PROGMEM,
};

Ft_Esd_BitmapCell power(ft_uint16_t cell)
{
	return (Ft_Esd_BitmapCell){ 
		.Info = &power__Info, 
		.Cell = cell 
	};
}

#ifdef ESD_SIMULATION
Ft_Esd_BitmapCell power_0__Get__ESD() { return power(0); }
#endif

/* end of file */
