/*
This file is automatically generated
power_64
Header
*/

#ifndef power_64__H
#define power_64__H

#ifndef ESD_FUNCTION
#define ESD_FUNCTION(name, ...)
#endif

#include "Ft_DataTypes.h"
#include "Ft_Esd_BitmapInfo.h"

Ft_Esd_BitmapCell power_64(ft_uint16_t cell);

extern Ft_Esd_BitmapInfo power_64__Info;

ESD_FUNCTION(power_64_0, Type = Ft_Esd_BitmapCell, DisplayName = "power_64", Include = "power_64.h", Category = _GroupUserResources, Icon = ":/icons/image.png", Macro)
#define power_64_0() ((Ft_Esd_BitmapCell){ .Info = &power_64__Info, .Cell = 0 })

#endif /* power_64__H */

/* end of file */
