/*
This file is automatically generated
power_stroke_icon
Header
*/

#ifndef power_stroke_icon__H
#define power_stroke_icon__H

#ifndef ESD_FUNCTION
#define ESD_FUNCTION(name, ...)
#endif

#include "Ft_DataTypes.h"
#include "Ft_Esd_BitmapInfo.h"

Ft_Esd_BitmapCell power_stroke_icon(ft_uint16_t cell);

extern Ft_Esd_BitmapInfo power_stroke_icon__Info;

ESD_FUNCTION(power_stroke_icon_0, Type = Ft_Esd_BitmapCell, DisplayName = "power_stroke_icon", Include = "power_stroke_icon.h", Category = _GroupUserResources, Icon = ":/icons/image.png", Macro)
#define power_stroke_icon_0() ((Ft_Esd_BitmapCell){ .Info = &power_stroke_icon__Info, .Cell = 0 })

#endif /* power_stroke_icon__H */

/* end of file */
