/*
This file is automatically generated
return_white_icon
Header
*/

#ifndef return_white_icon__H
#define return_white_icon__H

#ifndef ESD_FUNCTION
#define ESD_FUNCTION(name, ...)
#endif

#include "Ft_DataTypes.h"
#include "Ft_Esd_BitmapInfo.h"

Ft_Esd_BitmapCell return_white_icon(ft_uint16_t cell);

extern Ft_Esd_BitmapInfo return_white_icon__Info;

ESD_FUNCTION(return_white_icon_0, Type = Ft_Esd_BitmapCell, DisplayName = "return_white_icon", Include = "return_white_icon.h", Category = _GroupUserResources, Icon = ":/icons/image.png", Macro)
#define return_white_icon_0() ((Ft_Esd_BitmapCell){ .Info = &return_white_icon__Info, .Cell = 0 })

#endif /* return_white_icon__H */

/* end of file */
