/*
This file is automatically generated
right_curtain1
Header
*/

#ifndef right_curtain1__H
#define right_curtain1__H

#ifndef ESD_FUNCTION
#define ESD_FUNCTION(name, ...)
#endif

#include "Ft_DataTypes.h"
#include "Ft_Esd_BitmapInfo.h"

Ft_Esd_BitmapCell right_curtain1(ft_uint16_t cell);

extern Ft_Esd_BitmapInfo right_curtain1__Info;

ESD_FUNCTION(right_curtain1_0, Type = Ft_Esd_BitmapCell, DisplayName = "right_curtain1", Include = "right_curtain1.h", Category = _GroupUserResources, Icon = ":/icons/image.png", Macro)
#define right_curtain1_0() ((Ft_Esd_BitmapCell){ .Info = &right_curtain1__Info, .Cell = 0 })

#endif /* right_curtain1__H */

/* end of file */
