/*
This file is automatically generated
window1
Header
*/

#ifndef window1__H
#define window1__H

#ifndef ESD_FUNCTION
#define ESD_FUNCTION(name, ...)
#endif

#include "Ft_DataTypes.h"
#include "Ft_Esd_BitmapInfo.h"

Ft_Esd_BitmapCell window1(ft_uint16_t cell);

extern Ft_Esd_BitmapInfo window1__Info;

ESD_FUNCTION(window1_0, Type = Ft_Esd_BitmapCell, DisplayName = "window1", Include = "window1.h", Category = _GroupUserResources, Icon = ":/icons/image.png", Macro)
#define window1_0() ((Ft_Esd_BitmapCell){ .Info = &window1__Info, .Cell = 0 })

#endif /* window1__H */

/* end of file */
