/*
This file is automatically generated
window3
C Source
*/

#include "window3.h"

#include "Ft_Gpu.h"
#include "window3_progmem.h"

Ft_Esd_BitmapInfo window3__Info = {
	ESD_BITMAP_DEFAULTS,
	.Width = 228,
	.Height = 137,
	.Format = L4,
	.Stride = 114,
	.Size = 15618,
	.ProgMem = window3_bin,
	.StorageSize = ((428 + 3) >> 2),
	.Cells = 1,
	.Compressed = 1,
	.Persistent = 0,
	.Type = ESD_RESOURCE_PROGMEM,
};

Ft_Esd_BitmapCell window3(ft_uint16_t cell)
{
	return (Ft_Esd_BitmapCell){ 
		.Info = &window3__Info, 
		.Cell = cell 
	};
}

#ifdef ESD_SIMULATION
Ft_Esd_BitmapCell window3_0__Get__ESD() { return window3(0); }
#endif

/* end of file */
