/*
This file is automatically generated
window2
C Source
*/

#include "window2.h"

#include "Ft_Gpu.h"
#include "window2_progmem.h"

Ft_Esd_BitmapInfo window2__Info = {
	ESD_BITMAP_DEFAULTS,
	.Width = 230,
	.Height = 136,
	.Format = L4,
	.Stride = 115,
	.Size = 15640,
	.ProgMem = window2_bin,
	.StorageSize = ((461 + 3) >> 2),
	.Cells = 1,
	.Compressed = 1,
	.Persistent = 0,
	.Type = ESD_RESOURCE_PROGMEM,
};

Ft_Esd_BitmapCell window2(ft_uint16_t cell)
{
	return (Ft_Esd_BitmapCell){ 
		.Info = &window2__Info, 
		.Cell = cell 
	};
}

#ifdef ESD_SIMULATION
Ft_Esd_BitmapCell window2_0__Get__ESD() { return window2(0); }
#endif

/* end of file */
