/*
This file is automatically generated
window3
Header
*/

#ifndef window3__H
#define window3__H

#ifndef ESD_FUNCTION
#define ESD_FUNCTION(name, ...)
#endif

#include "Ft_DataTypes.h"
#include "Ft_Esd_BitmapInfo.h"

Ft_Esd_BitmapCell window3(ft_uint16_t cell);

extern Ft_Esd_BitmapInfo window3__Info;

ESD_FUNCTION(window3_0, Type = Ft_Esd_BitmapCell, DisplayName = "window3", Include = "window3.h", Category = _GroupUserResources, Icon = ":/icons/image.png", Macro)
#define window3_0() ((Ft_Esd_BitmapCell){ .Info = &window3__Info, .Cell = 0 })

#endif /* window3__H */

/* end of file */
