/*
This file is automatically generated
window2
Header
*/

#ifndef window2__H
#define window2__H

#ifndef ESD_FUNCTION
#define ESD_FUNCTION(name, ...)
#endif

#include "Ft_DataTypes.h"
#include "Ft_Esd_BitmapInfo.h"

Ft_Esd_BitmapCell window2(ft_uint16_t cell);

extern Ft_Esd_BitmapInfo window2__Info;

ESD_FUNCTION(window2_0, Type = Ft_Esd_BitmapCell, DisplayName = "window2", Include = "window2.h", Category = _GroupUserResources, Icon = ":/icons/image.png", Macro)
#define window2_0() ((Ft_Esd_BitmapCell){ .Info = &window2__Info, .Cell = 0 })

#endif /* window2__H */

/* end of file */
